### PR TITLE
Fix incorrect param name

### PR DESCRIPTION
**Pull request by gauravmc**
cc @chrisdonaldson

### CODE REVIEW

**Comment by chrisdonaldson** [comment]
We use the same parameter name in https://github.com/Shopify/asset_cloud/blob/master/lib/asset_cloud/buckets/blackhole_bucket.rb I would say either change both or neither. I don't have strong opinions either way.

I would also suggest if we're going to change it we might as well make it consistent with the rest of the buckets while we're at it and give them both an = nil.

```ruby
def ls(namespace = nil)
```

@bouk

**Comment by gauravmc** [comment]
Don't think we need to set a default on the param here since `ls` can never be used without a bucket name and we expect this to raise for same reason. Changed name, `namespace` is right

**Comment by chrisdonaldson** [comment]
I'm just thinking it makes it easier to swap these in for testing but I agree it's unlikely.

:+1:

**Comment by bouk** [comment]
Lgtm

**Pull request merged**
